/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InvoiceService;

public class InvoiceGenerator {
    public double calculateFare(double distance,int time) {
    	return 0;
    }
}
