/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InvoiceService;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;

public class InvoiceServiceTest {
	@Test
	public void givenDistanceAndTime_ShouldReturnTotalFare() {
		InvoiceGenerator invoiceGenerator = new InvoiceGenerator();
		double distance = 2.0;
		int time = 5;
		double fare = invoiceGenerator.calculateFare(distance, time);
		assertEquals(25, fare, 0.0);
	}

	@Test
	public void givenLessDistanceAndTime_ShouldReturnMinimumFare() {
		InvoiceGenerator invoiceGenerator = new InvoiceGenerator();
		double distance = 0.1;
		int time = 1;
		double fare = invoiceGenerator.calculateFare(distance, time);
		assertEquals(5, fare, 0.0);
	}

	@Test
	public void givenMultipleWrites_ShouldReturnInvoiceSummary() {
		InvoiceGenerator invoiceGenerator = new InvoiceGenerator();
		Ride[] rides = { new Ride(2.0, 5), new Ride(0.1, 1) };
		InvoiceSummary fare = invoiceGenerator.calculateFare(rides);
		InvoiceSummary expected = new InvoiceSummary(2,30);
		assertEquals(expected, fare);
	}
	
	@Test
	public void givenUserId_ShouldReturnListOfRides() {
		RideRepository rideRepository = new RideRepository();
		Ride ride1 = new Ride(2,5);
		Ride ride2 = new Ride(1,4);
		Ride ride3 = new Ride(0.1,1);
		
		rideRepository.addRide("abc",ride1);
		rideRepository.addRide("xyz",ride2);
		rideRepository.addRide("abc",ride3);
		
		Ride[] rides = rideRepository.getRides("abc");
		assertEquals(2,rides.length);
	}
}
