/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InvoiceService;

import org.junit.Test;
import static org.junit.Assert.*;

public class InvoiceServiceTest {
    @Test
    public void givenDistanceAndTime_ShouldReturnTotalFare() {
    	InvoiceGenerator invoiceGenerator = new InvoiceGenerator();
    	double distance = 2.0;
    	int time = 5;
    	double fare = invoiceGenerator.calculateFare(distance,time);
    	assertEquals(25,fare,0.0);
    }
}
